apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: python-demo

  template:
    metadata:
      labels:
        app: python-demo

    spec:
      containers:
      - name: python-demo
        image: python:3.10

        workingDir: /app

        command: ["/bin/sh", "-c"]
        args:
          - pip install flask && python app.py

        ports:
        - containerPort: 5000

        volumeMounts:
        - name: app
          mountPath: /app

      volumes:
      - name: app
        configMap:
          name: python-app